# Generated by Django 5.2 on 2025-05-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('distrito', models.CharField(max_length=10, verbose_name='Distrito')),
                ('subdistrito', models.CharField(max_length=10, verbose_name='Subdistrito')),
                ('setor', models.CharField(max_length=10, verbose_name='Setor')),
                ('numero_quadra', models.CharField(max_length=10, verbose_name='Nº da Quadra')),
                ('numero_face', models.CharField(max_length=10, verbose_name='Nº da Face')),
                ('seq_endereco', models.CharField(max_length=10, verbose_name='Seq Endereço')),
                ('seq_coletivo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Seq Coletivo')),
                ('seq_especie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Seq Espécie')),
                ('especie_domicilio', models.CharField(choices=[('1', 'Domicílio Particular Permanente Ocupado'), ('5', 'Domicílio Particular Improvisado Ocupado'), ('6', 'Domicílio Coletivo com Morador')], max_length=1, verbose_name='Espécie de Domicílio Ocupado')),
                ('tipo', models.CharField(choices=[('011', 'Casa'), ('012', 'Casa de vila ou em condomínio'), ('013', 'Apartamento'), ('014', 'Habitação em casa de cômodos ou cortiço'), ('015', 'Habitação indígena sem paredes ou maloca'), ('106', 'Estrutura residencial permanente degradada ou inacabada'), ('051', 'Tenda ou barraca de lona, plástico ou tecido'), ('052', 'Dentro do estabelecimento em funcionamento'), ('053', 'Outros (abrigos naturais e outras estruturas improvisadas)'), ('504', 'Estrutura improvisada em logradouro público, exceto tenda ou barraca'), ('505', 'Estrutura não residencial permanente degradada ou inacabada'), ('061', 'Asilo ou outra instituição de longa permanência para idosos'), ('062', 'Hotel ou pensão'), ('063', 'Alojamento'), ('064', 'Penitenciária, centro de detenção e similar'), ('065', 'Outro'), ('606', 'Abrigo, albergue ou casa de passagem para população em situação de rua'), ('607', 'Abrigo, casas de passagem ou república assistencial para outros grupos vulneráveis'), ('608', 'Clínica psiquiátrica, comunidade terapêutica e similar'), ('609', 'Orfanato e similar'), ('610', 'Unidade de internação de menores'), ('611', 'Quartel ou outra organização militar'), ('506', 'Veículos (Carros, Caminhões, Trailers, Barcos etc.)'), ('071', 'Asilo ou outra instituição de longa permanência para idosos')], max_length=3, verbose_name='Tipo')),
            ],
        ),
    ]
