# Generated by Django 5.2.1 on 2025-05-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domicilio',
            new_name='InformacaoDomicilio',
        ),
    ]
