# Generated by Django 5.2.1 on 2025-05-14 23:40

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0003_informacaomorador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Morador')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='InformacaoMorador',
        ),
        migrations.RenameModel(
            old_name='InformacaoDomicilio',
            new_name='Domicilio',
        ),
        migrations.AddField(
            model_name='morador',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='myapp.domicilio'),
        ),
    ]
