# Generated by Django 5.2 on 2025-05-15 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_morador_delete_informacaomorador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='morador',
            field=models.ForeignKey(default= 1 , on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='myapp.morador'),
        ),
    ]
