# Generated by Django 5.2 on 2025-05-15 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_morador_domicilio_domicilio_morador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='morador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='myapp.morador'),
        ),
    ]
