# Generated by Django 5.2.1 on 2025-05-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_domicilio_morador'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='acesso_agua_rede',
            field=models.BooleanField(default=False, help_text='O domicílio tem acesso geral à rede de distribuição de água?', verbose_name='Acesso geral à rede de distribuição de água?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quantidade_comodos',
            field=models.PositiveIntegerField(default=1, help_text='Número de cômodos deste domicílio', verbose_name='Quantidade de Cômodos'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quantidade_moradores',
            field=models.PositiveIntegerField(default=1, help_text='Número de pessoas que moram neste domicílio', verbose_name='Quantidade de Moradores'),
        ),
    ]
