# Generated by Django 5.2 on 2025-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_domicilio_acesso_agua_rede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='relacao_com_responsavel',
            field=models.CharField(choices=[('01', 'Pessoa responsável pelo domicílio'), ('02', 'Cônjuge ou companheiro(a) de sexo diferente'), ('03', 'Cônjuge ou companheiro(a) do mesmo sexo'), ('04', 'Filho(a) do responsável e do cônjuge'), ('05', 'Filho(a) somente do responsável'), ('06', 'Enteado(a)'), ('07', 'Genro ou nora'), ('08', 'Pai, mãe, padrasto ou madrasta'), ('09', 'Sogro(a)'), ('10', 'Neto(a)'), ('11', 'Bisneto(a)'), ('12', 'Irmão ou irmã'), ('13', 'Avô ou avó'), ('14', 'Outro parente'), ('15', 'Agregado(a)'), ('16', 'Convivente'), ('17', 'Pensionista'), ('18', 'Empregado(a) doméstico(a)'), ('19', 'Parente do(a) empregado(a) doméstico(a)'), ('20', 'Individual em domicílio coletivo')], default=1, max_length=2, verbose_name='Relação com o Responsável pelo Domicílio'),
        ),
    ]
