# Generated by Django 5.2 on 2025-05-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_morador_relacao_com_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='abastecimento_agua',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Como está sendo feito o abastecimento de água no domicílio'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='abastecimento_energia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Como está sendo feito o abastecimento de energia elétrica no domicílio'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='acesso_internet',
            field=models.BooleanField(default=False, verbose_name='Algum morador tem acesso a internet no domicílio?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='demandas_basicas',
            field=models.TextField(blank=True, null=True, verbose_name='Principais demandas de necessidades básicas'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='energia_internet',
            field=models.BooleanField(default=False, verbose_name='Chega energia elétrica e conexão de internet no domicílio?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='maquina_lavar_roupa',
            field=models.BooleanField(default=False, verbose_name='Tem uma máquina de lavar roupa?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='nome_rua',
            field=models.CharField(blank=True, choices=[('R. Marina do Sol', 'R. Marina do Sol'), ('R. Marina do Frade', 'R. Marina do Frade'), ('R. Marina dos Coqueiros', 'R. Marina dos Coqueiros'), ('R. Marina da Lua', 'R. Marina da Lua'), ('R. Marina do Bosque', 'R. Marina do Bosque'), ('R. Marina Porto Bali', 'R. Marina Porto Bali'), ('R. Marina das Flores', 'R. Marina das Flores'), ('R. Marina das Estrelas', 'R. Marina das Estrelas'), ('R. Marina Ponta Leste', 'R. Marina Ponta Leste')], max_length=50, null=True, verbose_name='Nome da rua'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da casa'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='perguntas_religiao_indigena',
            field=models.TextField(blank=True, null=True, verbose_name='Perguntas sobre religião e relacionadas a indígenas'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='pontos_coleta_lixo',
            field=models.TextField(blank=True, null=True, verbose_name='Pontos de coleta de lixo específicos da residência'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quantidade_banheiros_chuveiro',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Banheiros com chuveiro e vaso sanitário'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quantidade_banheiros_sem_chuveiro',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Banheiros sem chuveiro mas com vaso sanitário'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quantidade_dormitorios',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de dormitórios para os moradores'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='relacao_outras_ilhas',
            field=models.TextField(blank=True, null=True, verbose_name='Como funciona a relação com as outras ilhas'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='situacao_imovel',
            field=models.CharField(blank=True, choices=[('A', 'Ainda pagando'), ('L', 'Alugado'), ('E', 'Por empregador'), ('F', 'Por familiar'), ('O', 'Outra forma'), ('C', 'Outra condição'), ('J', 'Já pago, herdado ou ganho')], max_length=1, null=True, verbose_name='Situação do imóvel'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tempo_conclusao_falecimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo para conclusão do processo de falecimento'),
        ),
        migrations.AddField(
            model_name='morador',
            name='atividade_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Principal atividade do negócio ou empresa'),
        ),
        migrations.AddField(
            model_name='morador',
            name='autismo_diagnostico',
            field=models.BooleanField(default=False, verbose_name='Já foi diagnosticado(a) com autismo por profissional de saúde?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='carteira_assinada',
            field=models.BooleanField(default=False, verbose_name='Carteira de trabalho assinada?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='concluiu_superior',
            field=models.BooleanField(default=False, verbose_name='Já concluiu algum outro curso superior de graduação?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='contato_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail para contato'),
        ),
        migrations.AddField(
            model_name='morador',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome para contato'),
        ),
        migrations.AddField(
            model_name='morador',
            name='contato_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para contato'),
        ),
        migrations.AddField(
            model_name='morador',
            name='curso_frequentado',
            field=models.CharField(blank=True, choices=[('1', 'Pré escola'), ('2', 'Creche'), ('3', 'Alfabetização de jovens e adultos'), ('4', 'Regular do ensino fundamental'), ('5', 'EJA do ensino fundamental'), ('6', 'Regular do ensino médio'), ('7', 'Superior de graduação'), ('8', 'EJA do ensino médio'), ('9', 'Especialização de nível superior'), ('10', 'Mestrado'), ('11', 'Doutorado'), ('12', 'Nenhum')], max_length=2, null=True, verbose_name='Curso que frequenta'),
        ),
        migrations.AddField(
            model_name='morador',
            name='dificuldade_andar',
            field=models.CharField(blank=True, choices=[('1', 'Tem muita dificuldade'), ('2', 'Tem, não consegue de modo algum'), ('3', 'Tem alguma dificuldade'), ('4', 'Não tem dificuldade')], max_length=1, null=True, verbose_name='Dificuldade para andar ou subir degraus'),
        ),
        migrations.AddField(
            model_name='morador',
            name='dificuldade_enxergar',
            field=models.CharField(blank=True, choices=[('1', 'Tem, não consegue de modo algum'), ('2', 'Tem muita dificuldade'), ('3', 'Tem alguma dificuldade'), ('4', 'Não tem dificuldade')], max_length=1, null=True, verbose_name='Dificuldade para enxergar'),
        ),
        migrations.AddField(
            model_name='morador',
            name='empresa_cnpj',
            field=models.BooleanField(default=False, verbose_name='Empresa registrada no CNPJ?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='faixa_rendimento',
            field=models.CharField(blank=True, choices=[('1', '1,00 a 500,00'), ('2', '501,00 a 1.000,00'), ('3', '1.001,00 a 2.000,00'), ('4', '2.001,00 a 3.000,00'), ('5', '3.001,00 a 5.000,00'), ('6', '5.001,00 a 10.000,00'), ('7', '10.001,00 a 20.000,00'), ('8', '20.001,00 a 100.000'), ('9', '100.001 ou mais')], max_length=2, null=True, verbose_name='Faixa de rendimento'),
        ),
        migrations.AddField(
            model_name='morador',
            name='frequenta_escola',
            field=models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não, mas já frequentou'), ('3', 'Não, nunca frequentou')], max_length=1, null=True, verbose_name='Frequenta escola ou creche?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='local_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de trabalho'),
        ),
        migrations.AddField(
            model_name='morador',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do cônjuge'),
        ),
        migrations.AddField(
            model_name='morador',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupação, cargo ou função'),
        ),
        migrations.AddField(
            model_name='morador',
            name='possui_conjuge',
            field=models.BooleanField(default=False, verbose_name='Possui cônjuge ou companheiro(a)?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='principal_transporte',
            field=models.CharField(blank=True, choices=[('1', 'A pé'), ('2', 'Bicicleta'), ('3', 'Motocicleta'), ('4', 'Mototáxi'), ('5', 'Automóvel'), ('6', 'Táxi ou assemelhados'), ('7', 'Van, perua ou assemelhados'), ('8', 'Ônibus'), ('11', 'Caminhonete ou caminhão adaptado'), ('12', 'Embarcação de médio e grande porte'), ('13', 'Embarcação de pequeno porte'), ('14', 'Outros')], max_length=2, null=True, verbose_name='Principal meio de transporte'),
        ),
        migrations.AddField(
            model_name='morador',
            name='qtd_trabalhos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantos trabalhos tinha nos últimos meses?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='registro_nascimento',
            field=models.CharField(blank=True, choices=[('cartorio', 'Do cartório'), ('indigena', 'Registro administrativo de nascimento indígena'), ('nao_tem', 'Não tem'), ('nao_sabe', 'Não sabe')], max_length=50, null=True, verbose_name='Registro de nascimento'),
        ),
        migrations.AddField(
            model_name='morador',
            name='religiao_culto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual é sua religião ou culto?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='retorna_casa',
            field=models.BooleanField(default=False, verbose_name='Retorna do trabalho para casa 3 dias ou mais na semana?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='sabe_ler_escrever',
            field=models.BooleanField(default=False, verbose_name='Sabe ler e escrever?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='tempo_casa_trabalho_horas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Horas entre casa e trabalho'),
        ),
        migrations.AddField(
            model_name='morador',
            name='tempo_casa_trabalho_minutos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Minutos entre casa e trabalho'),
        ),
        migrations.AddField(
            model_name='morador',
            name='tipo_uniao',
            field=models.CharField(blank=True, choices=[('civil_religioso', 'Casamento civil e religioso'), ('civil', 'Só casamento civil'), ('religioso', 'Só casamento religioso'), ('consensual', 'União consensual')], max_length=30, null=True, verbose_name='Tipo da união'),
        ),
        migrations.AddField(
            model_name='morador',
            name='trabalhou_remunerado',
            field=models.BooleanField(default=False, verbose_name='Trabalhou ou estagiou em atividade remunerada?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='vive_com_conjuge',
            field=models.BooleanField(default=False, verbose_name='Vive em companhia de cônjuge ou companheiro(a)?'),
        ),
    ]
