site_name: PBE_25.1_8002_Grupo1

theme:
  name: mkdocs
  palette:
    primary: blue
    
  locale: pt_BR
  language: pt-BR

  font:
    text: Roboto
    code: Roboto Mono
  user_color_mode_toggle: true


